import { modifyAge, modifyGender } from '@/common/utils/formats';
import type { HttpMeta } from '@/dicom/DicomInterface';
import type { QueryParamsBase } from '@/index.d';
import type { Meta } from './index.d';
import type { Study } from '@/dicom';
declare const modifyDA: (value: string) => string;
declare const modifyTM: (value: string) => string;
declare const pureData: (data: HttpMeta, queryParams: QueryParamsBase, study: Study) => Meta;
export { pureData, modifyTM, modifyDA, modifyAge, modifyGender };
export default pureData;
