/** @prettier  */
import type { DicomInfoProps } from './DicomInterface';
/** @deprecated */
declare class DicomInfo {
    /** @deprecated */
    accnum: string;
    acqdt: string;
    acqtm?: string;
    age: string;
    birth: string;
    bita: number;
    bits: string;
    blocks: number;
    col: number;
    hbit: string;
    id?: string;
    imageIcon?: string;
    imgnum: string;
    imgori?: string;
    imgpos?: string;
    inst: string;
    isLoadImage: boolean;
    kv: string;
    ma?: string;
    manu: string;
    mod: string;
    name: string;
    num: string;
    orb: string;
    orl: string;
    orr: string;
    ort: string;
    patid: string;
    phme: string;
    pixrep: number;
    pixx: number;
    pixy: number;
    rescin: number;
    rescsl: number;
    row: number;
    sappix: number;
    serdes: string;
    serid: string;
    seruid: string;
    sex: string;
    sliceth: string;
    sopuid: string;
    strScount?: string;
    studes: string;
    studt: string;
    stuid: string;
    stutm: string;
    stuuid: string;
    syntaxuid?: string;
    uid?: string;
    wc: number;
    ww: number;
    constructor(dicomInfo: DicomInfoProps);
}
export default DicomInfo;
