import MovePopup from '../components/Popup/MovePopup';
import PageState, { type State } from './store/PageState';
import './index.less';
export declare class StitchingLayout {
    eventNamespace: string;
    studyUID?: string;
    size: number[];
    zoom: number;
    private _isInit;
    movePopup?: MovePopup;
    gridContainer: HTMLElement;
    configContainer?: HTMLElement;
    viewerContainer?: HTMLElement;
    activeContainer?: HTMLElement;
    pageState: PageState;
    get isInit(): boolean;
    private set isInit(value);
    getImagesContainer(): NodeListOf<HTMLElement>;
    setToolEnable(type: string, visibility: boolean): void;
    setTool(type: string): void;
    setSize(size: number[]): void;
    setZoom(): void;
    getActiveViewerContainer(): HTMLElement;
    initLayout(): Promise<void>;
    private createConfigLayout;
    initGridLayout(): void;
    private gridEvents;
    toggleDisableViewerContainer: any;
    toggleActiveViewerContainer(force?: boolean): void;
    private isMove;
    imageToggle(target: HTMLElement, show?: boolean): void;
    renderStitchingImage(): Promise<void>;
    addToStudy: {
        (...args: any[]): any;
        cancel: () => void;
        flush: () => any;
        pending: () => boolean;
    };
    stitchingSave(): Promise<void>;
    initCanvas(pageImage: State, container: HTMLElement): Promise<void>;
    private canvasToPixel;
    renderPixelData(): Promise<any>;
    hasActive(): Promise<void>;
    syncImages(): void;
    updateImages(): void;
    disableImage(element?: HTMLElement | undefined): void;
    disableImages(): void;
    resizeImages(): void;
    callImages(callback: (canvas: HTMLElement) => void, strict?: boolean): void;
    close(): Promise<void>;
    destroy(): void;
    destroyGridLayout(): void;
}
declare const stitching: StitchingLayout;
declare const version: any;
export { version };
export default stitching;
