/** @prettier  */
import { Viewport } from 'cornerstone-core';
import ImageTypeLayout, { ImageTypeEventsData } from '@/views/components/imageTypeLayout';
import WWWCLayout from '@/views/components/WWWCLayout';
import RotatePop from '@/views/components/rotatePop';
import ColorMap from '@/views/components/colorMap';
import ScaleLayout, { ScaleLayoutDataItem } from '@/views/components/scaleLayout';
import SeriesMarker from '@/views/components/seriesMarker';
import SeriesImageCruxMarker from './components/seriesImageCruxMarker';
import TopTools from '@/views/components/topTools';
import SeriesSlider from '@/views/components/seriesSlider';
import StudySlider from '@/views/components/studySlider';
import StudyMenuLayout from '@/views/components/studyMenuLayout';
import IconPlayer from '@/views/components/iconPlayer';
import SeriesLayout from '@/views/components/seriesLayout';
import VRTOrMPRLayout from '@/views/components/VRTOrMPRLayout';
import IconSynchronizer from '@/views/components/iconSynchronizer';
import ThicknessLayout from './components/thicknessLayout';
import FusionLayout from '@/views/components/fusionLayout';
import FusionLayout2 from '@/views/components/fusionLayout2';
import IntelGPULayout from '@/views/components/IntelGPULayout';
import { ToolData } from '@/store/toolDataOrigin';
import store from '@/store/app';
import type { PtCell } from '@/dicom/DicomInterface';
import type { Series, Study } from '@/dicom';
import type { Meta } from '@/common/metaData/index.d';
import type { WWWCMenuItem } from '@hs/store/form/other';
declare class DicomLayoutView {
    topTools: TopTools;
    imageTypeLayout: ImageTypeLayout;
    wwwcLayout: WWWCLayout;
    scale: ScaleLayout;
    rotatePop: RotatePop;
    colorMap: ColorMap;
    seriesMarker: SeriesMarker;
    seriesImageCruxMarker: SeriesImageCruxMarker;
    seriesSlider: SeriesSlider;
    studySlider: StudySlider;
    studyMenuLayout?: StudyMenuLayout;
    seriesLayout: SeriesLayout;
    iconPlayer: IconPlayer;
    ThicknessLayout: ThicknessLayout;
    FusionLayout: FusionLayout;
    FusionLayout2: FusionLayout2;
    IntelGPULayout: IntelGPULayout;
    mprLayout: VRTOrMPRLayout;
    vrtLayout: VRTOrMPRLayout;
    iconSynchronizer: IconSynchronizer;
    /****************/
    toolsData: ToolData[];
    toolsDataMPR: ToolData[];
    toolsDataVRT: ToolData[];
    toolsContainer: HTMLElement;
    logoGrouper: HTMLElement;
    navBarContainer: HTMLElement;
    studyNavigationHead: HTMLElement;
    studyNavigationBody: HTMLElement;
    canvasContainer: HTMLElement;
    constructor();
    resizeLayout(parentContainer?: HTMLElement): void;
    createImageTypeLayout(event: any): void;
    createWWWCLayout(event: any): void;
    createRotateLayout(event: any): void;
    createScaleLayout(event: any): void;
    createColorMapLayout(event: any): void;
    createDICOMMetaInfoLayout(dicomMetaData: any): void;
    createAboutUsLayout(aboutUs: typeof store.aboutUs): void;
    createImageLayout(imageUrl: string, fileName?: string): void;
    createSeriesMarker(container: HTMLElement, series: Series, meta: Meta, viewport: Viewport): void;
    imageTypeMark(): void;
    imageType(data: ImageTypeEventsData): void;
    wwwcImage($canvas: HTMLElement, data: WWWCMenuItem): void;
    scaleImage($canvas: HTMLElement, data: ScaleLayoutDataItem): void;
    rotateImage($canvas: HTMLElement, rotateFlag: string): void;
    colorMapImage($canvas: HTMLElement, colorId: string): void;
    createSeriesCellLayout(event: any, className: string, callback: (...args: any[]) => void, layoutCell: PtCell, layoutCellActive?: PtCell): void;
    initLayout(globalContainer: HTMLElement): void;
    initTop2DTools(toolTag?: string, force?: boolean): void;
    initTopMPRTools(toolTag: string, force?: boolean): void;
    initTopVRTTools(toolTag?: string, force?: boolean): void;
    createStudyNavigationGroup(study: Study, studyIndex: number, isMultiStudy: boolean): void;
    renderDicomIcon(container: HTMLElement, seriesArr: Array<Series>, studyIndex: number): void;
    renderStudyInfo(container: HTMLElement, study: Study, imagesLength: number): void;
    navigatorStudyToggleStyle(parentContainer: HTMLElement, childCount: number, force?: boolean): boolean | void;
    seriesBarToggle(show?: boolean): void;
    seriesBarIconToggle(show?: boolean): void;
    navigationMenuCloseHandle(resize?: boolean): Promise<void>;
    selectPopupHidden(): void;
    removeOpenMark(): void;
    toggleToolStyle(toolParams?: ToolData & {
        btnOriginTarget?: HTMLElement;
        btnTarget?: HTMLElement;
        parentData?: ToolData;
    }): void;
    gridHoverStyle(gridLayout: HTMLElement, selectPt: PtCell): void;
    progressCountStyle(seriesUID: string, totalLength?: number, count?: number, showProgress?: boolean): void;
    toggleCavanAroundInfoStyle(visibility: boolean): void;
    toggleAIIconStyle(seriesUIDArr?: string[]): void;
    querySelector<T extends Element = HTMLElement>(selectors: string, options?: {
        tip: boolean;
    }): T;
    querySelectorForTool<T extends Element = HTMLElement>(selectors: string, parent?: string, options?: {
        tip: boolean;
    }): T;
    containsClassName(container: HTMLElement, selector: string): boolean;
    clearSeriesLayout(seriesDom: HTMLElement, ignoreBaseDom?: boolean, ignoreDataset?: boolean): void;
}
export default DicomLayoutView;
